# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_percent', models.DecimalField(decimal_places=10, max_digits=30)),
                ('deposit_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('withdraw_percent', models.DecimalField(decimal_places=10, max_digits=30)),
                ('withdraw_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_order_percent', models.DecimalField(decimal_places=10, max_digits=30)),
                ('book_order_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('market_order_percent', models.DecimalField(decimal_places=10, max_digits=30)),
                ('market_order_value', models.DecimalField(decimal_places=10, max_digits=25)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='exchange.Exchange_Currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_currency', to='exchange.Exchange_Currency')),
            ],
        ),
    ]
