# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_pair',
            name='exchange',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exchange.Exchange'),
        ),
        migrations.AlterField(
            model_name='exchange_pair',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='exchange.Currency'),
        ),
        migrations.AlterField(
            model_name='exchange_pair',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_currency', to='exchange.Currency'),
        ),
    ]
