# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-12 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_order_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('unix', models.DecimalField(decimal_places=10, max_digits=30)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
